### ISSUE TITLE
windows 版本的客户端放不出音乐

### ISSUE THREAD

**Issue by Haimianbaby** [i5sing/i5SING#10]
错误提示 Uncaught (in promise) DOMException: Failed to load because no supported source was found.

**Comment by miaowing** [comment]
请下载最新版本 https://github.com/i5sing/i5SING/releases/tag/v0.2.0-alpha0，谢谢，老版本不再维护了，目前可能有一些功能未完善和一些bug，近期会修复。

**Comment by miaowing** [comment]
#9

**Comment by Haimianbaby** [comment]
好的，希望大佬越做越好

**Comment by miaowing** [comment]
0.2.0 Released
