### ISSUE TITLE
Disable the text selected when adjusting progress or volume.

### ISSUE THREAD

**Issue by sonack** [i5sing/i5SING#11]
当调整播放进度时，很容易选中文字，如下：
![image](https://user-images.githubusercontent.com/12935189/61038440-a44cdf00-a3ff-11e9-88bd-3009b7013d7a.png)
能不能禁止掉可选呢？

**Comment by miaowing** [comment]
Fixes in #13

**Comment by sonack** [comment]
![image](https://user-images.githubusercontent.com/12935189/65041012-5ec10b00-d988-11e9-920c-9e849e6e8d49.png)
在歌曲列表界面双击播放的话，还是会选中文字，这是Bug还是feature?
