### ISSUE TITLE
bug反馈：音乐列表点出来就关不掉了

### ISSUE THREAD

**Issue by LewisTian** [i5sing/i5SING#12]
如下，随便试了一个歌单，然后点出来播放列表，之后不管点哪音乐列表都关不掉 ;O

![Snipaste_2019-07-15](https://user-images.githubusercontent.com/23132915/61192638-84136d80-a6e8-11e9-903b-0c217bf118b9.png)

**Comment by miaowing** [comment]
感谢反馈

**Comment by miaowing** [comment]
Fixes in #13
