### ISSUE TITLE
这个厉害了

### ISSUE THREAD

**Issue by xyeric** [i5sing/i5SING#4]
官方没有提供pc客户端，在github上搜了好多都是api，正好想同 electron 做一个简单一点的自己用来着，看到这个真心感觉很赞

**Comment by eric-cheung** [comment]
目前还存在一些小问题：

- 用户感知上，比如说搜索歌曲的时候半天没出来，又没用loading，以为用不了呢。
- 还有没有登录的时候没有默认头像，显示出来的那个框框不太好看。
- 我的音乐里面，个人信息显示为null。



还有就是后续可以像网易云音乐一样做个播放的页面，歌词可以滚动的。

**Comment by miaowing** [comment]
感谢反馈~，下一个版本会加上。
歌词滚动这个还要再看看有没有必要，5sing上的lrc歌词不是很多。

**Comment by airfey** [comment]
请问根目录下的build目录的内容在哪里？

**Comment by miaowing** [comment]
原 build 目录内的文件已经移到 scripts 目录中，最新的 commit 已经修复 npm script。 @airfey 感谢反馈~。

**Comment by airfey** [comment]
@miaowing 感谢，刚接触electron，正在学习中，作为参考是很好的demo

**Comment by zx122only** [comment]
怎么更新新版本？

**Comment by miaowing** [comment]
目前通过 http://beta.i5sing.com 下载的就是最新版本~。 @zx122only

**Comment by zx122only** [comment]
万分感谢～～

**Comment by zx122only** [comment]
之前下载的客户端提醒更新，但是怎么也找不到新的客户端下载网址，谢谢～加油～

**Comment by miaowing** [comment]
感谢支持，最初使用的是第三方的版本管理系统，目前已经废弃并切换到从 i5sing 官网检查版本，所以造成版本检查异常，导致无网址。@zx122only

**Comment by zx122only** [comment]
好哒，那以后要是升级的话不会换网址了吧

**Comment by miaowing** [comment]
@zx122only，是哒~。

**Comment by zx122only** [comment]
好哒～
