### ISSUE TITLE
已经不维护了吗？获取用户歌曲列表的API接口好像变了？

### ISSUE THREAD

**Issue by sonack** [i5sing/i5SING#6]
有个API的返回结果变了

获取用户歌曲只能返回10首(虽然你们请求的pagesize好像是20)
[get] http://mobileapi.5sing.kugou.com/song/user

我利用了这个API，写过一个linux下的命令行版本，下面是我的偷懒的fix方式，我发现虽然只能返回10首，但是传入pageindex还是可以不断获得下一页的10首的，所以我不断查询下一页 直到下一页为空 虽然很ugly，但是很easy，可以参考下[我的这个](https://github.com/sonack/5sing-Spider/blob/master/5singPlayer#L325)

**Comment by miaowing** [comment]
重新抓API看了一下，app的参数就是这样传的，可能是后端把页数写死了。
