### ISSUE TITLE
发现了几个bug :O

### ISSUE THREAD

**Issue by LewisTian** [i5sing/i5SING#8]
1. 每日推荐那部分信息不对（大概是 api 失效了
![每日推荐](https://user-images.githubusercontent.com/23132915/55868957-12db9000-5bb8-11e9-8ec4-3f0348c6de24.png)
2. #7 中所说新入驻音乐人第一张图的问题
![新入驻音乐人](https://user-images.githubusercontent.com/23132915/55869032-44545b80-5bb8-11e9-984f-d58aac1d7b1e.png)
3. 支持榜歌曲信息么得（大概也是 api 失效了
![支持榜歌曲信息](https://user-images.githubusercontent.com/23132915/55869115-7239a000-5bb8-11e9-8bef-e586f85c0440.png)

**Comment by miaowing** [comment]
感谢，目前正在开发新版本，还得等一段时间
