### ISSUE TITLE
V0.2.0 版本开发计划

### ISSUE THREAD

**Issue by miaowing** [i5sing/i5SING#9]
V0.2 版本使用 Typesciprt 重写整个客户端，全新设计并且支持更多特性：

[done]  1. 新增MV播放
[done]  2. 新增歌曲、MV、用户评论
[done]  3. 新增本地歌曲管理
[done]  4. 新增歌曲保存到云盘及上传本地歌曲到云盘
[done]  5. 支持跳到某一时刻播放
[done]  6. 支持音量控制
[done]  7. 支持Touch Bar
[done]  8. Mac 歌词显示

## demo UI：

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/12780562/57584283-e8108e80-750b-11e9-9996-d59420a1012d.png">

## download:

V0.2.0-alpha1:  https://github.com/i5sing/i5SING/releases/tag/v0.2.0-alpha1

1. Feature movie comment
2. Fix tray not display sometime

V0.2.0-alpha0:  https://github.com/i5sing/i5SING/releases/tag/v0.2.0-alpha0

**Comment by sonack** [comment]
音量控制， 进度拉取啥的有支持了吗？

**Comment by miaowing** [comment]
> 音量控制， 进度拉取啥的有支持了吗？

是哒，都支持了😁

**Comment by LewisTian** [comment]
哇 这个 UI 好看欸，我还想用 Qt 写一个，看来可以咕咕咕了😋

**Comment by miaowing** [comment]
> 哇 这个 UI 好看欸，我还想用 Qt 写一个，看来可以咕咕咕了😋

喵喵喵😝

**Comment by sonack** [comment]
很赞！

**Comment by miaowing** [comment]
Released, please visit  [https://i5sing.com](https://i5sing.com)  download
